// ===== THE COLD WAR FILES: CUBA — Complete Game Data =====

export const EVIDENCE_CATEGORIES = {
  photographs: { label: "Photographs", icon: "Camera", color: "text-amber-700" },
  newspapers: { label: "Newspaper Articles", icon: "Newspaper", color: "text-stone-600" },
  maps: { label: "Maps & Charts", icon: "Map", color: "text-emerald-800" },
  telegrams: { label: "Telegrams & Cables", icon: "Send", color: "text-blue-800" },
  propaganda: { label: "Propaganda", icon: "Megaphone", color: "text-red-800" },
  intelligence: { label: "Intelligence Reports", icon: "Shield", color: "text-slate-700" },
  speeches: { label: "Speeches & Transcripts", icon: "Mic", color: "text-purple-800" },
  civilian: { label: "Civilian Accounts", icon: "Users", color: "text-orange-700" },
  economic: { label: "Economic Records", icon: "TrendingUp", color: "text-green-800" },
  communications: { label: "Intercepted Comms", icon: "Radio", color: "text-red-700" },
};

export const EVIDENCE_FILES = [
  // === PHOTOGRAPHS ===
  {
    id: "photo_batista_palace",
    category: "photographs",
    title: "Batista at the Presidential Palace, 1957",
    date: "1957-03-15",
    classification: "UNCLASSIFIED",
    source: "Associated Press Archive",
    content: "A photograph showing President Fulgencio Batista surrounded by American business executives at a state dinner in Havana. Crystal chandeliers, champagne glasses, and imported cigars are visible. In the background, US Ambassador Earl Smith can be seen shaking hands with United Fruit Company representatives.",
    analysis_prompt: "What does this image tell us about the relationship between the Batista regime and American business interests?",
    connections: ["doc_batista_economy", "doc_sugar_trade", "doc_castro_speech_history"],
    unlocks: ["doc_mafia_havana"],
    tier: 1,
    perspective: "US Business",
  },
  {
    id: "photo_sierra_maestra",
    category: "photographs",
    title: "Guerrillas in Sierra Maestra, 1958",
    date: "1958-06-20",
    classification: "DECLASSIFIED",
    source: "Herbert Matthews / NY Times",
    content: "A grainy photograph of bearded revolutionaries in mountain terrain. Fidel Castro stands at the center addressing a group of approximately 40 fighters. Crude weapons, hammocks strung between trees, and a hand-drawn map pinned to a tree trunk are visible. A peasant farmer appears to be offering supplies to the group.",
    analysis_prompt: "Why might peasant farmers support the guerrilla movement? What conditions drove them to risk helping armed rebels?",
    connections: ["doc_matthews_interview", "doc_batista_economy", "doc_land_reform"],
    unlocks: ["doc_cia_guerrilla_assessment"],
    tier: 1,
    perspective: "Cuban Revolutionary",
  },
  {
    id: "photo_u2_missiles",
    category: "photographs",
    title: "U-2 Reconnaissance: San Cristóbal, Cuba",
    date: "1962-10-14",
    classification: "TOP SECRET // UMBRA",
    source: "CIA / National Reconnaissance Office",
    content: "Aerial reconnaissance photograph from a U-2 spy plane showing medium-range ballistic missile launch sites under construction near San Cristóbal, Cuba. Annotations identify: missile erectors, fuel tank trailers, oxidizer tank trailers, and tent areas. The pattern matches Soviet R-12 MRBM installations. Range estimate: 1,020 nautical miles — capable of striking Washington D.C.",
    analysis_prompt: "These photographs changed the course of history in hours. Why was aerial surveillance so critical, and what does the secrecy of the installation tell us about Soviet strategy?",
    connections: ["doc_excomm_transcript", "doc_khrushchev_letter", "doc_turkey_missiles"],
    unlocks: ["doc_secret_negotiations"],
    tier: 2,
    perspective: "US Intelligence",
  },
  {
    id: "photo_missile_parade",
    category: "photographs",
    title: "Soviet Missiles on Display, Red Square",
    date: "1961-11-07",
    classification: "UNCLASSIFIED",
    source: "TASS News Agency",
    content: "Photograph from the November 7th Revolution Day parade in Moscow. Massive R-12 medium-range ballistic missiles are being transported through Red Square on mobile launchers. Crowds cheer. Khrushchev watches from the reviewing stand atop Lenin's Mausoleum. A banner reads: 'The Socialist Camp — Invincible!'",
    analysis_prompt: "Why did the Soviet Union publicly display its missiles? What message was being sent, and to whom?",
    connections: ["doc_arms_race_data", "doc_khrushchev_fears"],
    unlocks: [],
    tier: 1,
    perspective: "Soviet",
  },

  // === NEWSPAPER ARTICLES ===
  {
    id: "doc_matthews_interview",
    category: "newspapers",
    title: "Herbert Matthews Interview with Castro",
    date: "1957-02-24",
    classification: "UNCLASSIFIED",
    source: "The New York Times",
    content: "CUBAN REBEL IS VISITED IN HIDEOUT\nBy Herbert L. Matthews\n\nSierra Maestra, Cuba — Fidel Castro, the rebel leader of Cuba's youth, is alive and fighting hard and successfully in the rugged, almost impenetrable fastnesses of the Sierra Maestra.\n\n\"We have been fighting for 79 days now and are stronger than ever,\" Señor Castro said. \"The soldiers are fighting badly; their morale is low. We are going to win.\"\n\nHe has strong ideas of liberty, democracy, social justice, the need to restore the constitution, and hold elections. He has no animosity toward the United States.\n\n\"You can be sure we have no animosity toward the United States and the American people,\" he assured me. \"We are fighting for a democratic Cuba and an end to the dictatorship.\"",
    analysis_prompt: "Castro claimed democratic ideals to the American press. Was this genuine, strategic, or both? How did this coverage shape American perception?",
    connections: ["photo_sierra_maestra", "doc_castro_speech_history", "doc_us_reaction_revolution"],
    unlocks: ["doc_cia_castro_assessment"],
    tier: 1,
    perspective: "American Media",
  },
  {
    id: "doc_pravda_blockade",
    category: "newspapers",
    title: "Pravda: 'American Piracy on the High Seas'",
    date: "1962-10-24",
    classification: "UNCLASSIFIED",
    source: "Pravda (Soviet State Newspaper)",
    content: "AMERICAN PIRACY ON THE HIGH SEAS\n\nThe aggressive circles of the United States of America have taken a step that has brought the world to the brink of thermonuclear catastrophe. The so-called \"quarantine\" announced by President Kennedy is nothing but a naval blockade — an act of war under international law.\n\nThe Soviet Union has repeatedly stated that its assistance to Cuba is purely defensive in nature. The weapons supplied to Cuba serve only to protect the sovereignty of a small nation against the aggressive designs of American imperialism.\n\nThe peoples of the world demand: HANDS OFF CUBA!",
    analysis_prompt: "How does the Soviet narrative differ from the American version? What words are chosen specifically to frame the US as the aggressor?",
    connections: ["doc_kennedy_address", "doc_soviet_un_response", "prop_soviet_poster_hands"],
    unlocks: [],
    tier: 2,
    perspective: "Soviet Media",
  },

  // === MAPS ===
  {
    id: "map_missile_range",
    category: "maps",
    title: "Estimated Missile Range from Cuba",
    date: "1962-10-16",
    classification: "SECRET",
    source: "CIA Cartographic Division",
    content: "A classified map showing concentric circles radiating from Cuba. The inner circle (1,020 nm) encompasses Washington D.C., Dallas, St. Louis, and most of the Eastern seaboard. The outer circle (2,200 nm — IRBM range) reaches nearly every major city in the continental United States, plus parts of Canada and Mexico. An estimated 80 million Americans live within strike range. Handwritten note in margin: 'Warning time: approximately 5 minutes.'",
    analysis_prompt: "How would this map have affected decision-making in the White House? What does '5 minutes warning time' mean for deterrence theory?",
    connections: ["photo_u2_missiles", "doc_excomm_transcript", "doc_turkey_missiles"],
    unlocks: ["doc_defcon_records"],
    tier: 2,
    perspective: "US Military",
  },
  {
    id: "map_turkey_missiles",
    category: "maps",
    title: "Jupiter Missile Installations in Turkey",
    date: "1961-06-01",
    classification: "SECRET // NOFORN",
    source: "NATO Strategic Planning",
    content: "Map showing 15 Jupiter IRBM launch sites positioned along Turkey's southern coast, aimed at the Soviet Union. Range circles show coverage of Moscow, Leningrad, Kiev, and major Soviet industrial centers. Deployment date: 1961. The Jupiter missiles are considered first-strike capable with a range of 1,500 miles.\n\nAnnotation from Soviet intelligence analysis: 'These missiles can destroy our command centers in 16 minutes. We have no comparable forward deployment.'",
    analysis_prompt: "If the US had missiles in Turkey aimed at Moscow, does the Soviet placement of missiles in Cuba look different? What does this map reveal about Cold War 'double standards'?",
    connections: ["doc_turkey_missiles", "doc_khrushchev_fears", "doc_secret_negotiations"],
    unlocks: ["doc_khrushchev_memoirs"],
    tier: 2,
    perspective: "Soviet Strategic",
  },

  // === TELEGRAMS ===
  {
    id: "doc_khrushchev_letter",
    category: "telegrams",
    title: "Khrushchev to Kennedy — October 26, 1962",
    date: "1962-10-26",
    classification: "TOP SECRET",
    source: "Soviet Embassy / State Department",
    content: "Mr. President,\n\nI understand your concern. You are worried about Cuba. We are worried about Turkey. I propose: we will remove our missiles from Cuba. You will remove yours from Turkey. Neither of us wants this weapons contest to go on, especially if it can lead to nuclear catastrophe.\n\nIf you have not lost your self-control and sensibly conceive what this might lead to, then, Mr. President, we and you ought not now to pull on the ends of the rope in which you have tied the knot of war, because the more the two of us pull, the tighter that knot will be tied.\n\nLet us not only relax the forces pulling on the ends of the rope, let us take measures to untie that knot. We are ready for this.\n\nRespectfully,\nN. Khrushchev",
    analysis_prompt: "This letter is remarkably personal and emotional for diplomatic communication. What does the 'rope' metaphor reveal about Khrushchev's state of mind?",
    connections: ["doc_excomm_transcript", "doc_turkey_missiles", "doc_secret_negotiations"],
    unlocks: ["doc_bobby_kennedy_backchannel"],
    tier: 3,
    perspective: "Soviet Leadership",
  },
  {
    id: "doc_castro_khrushchev_cable",
    category: "telegrams",
    title: "Castro to Khrushchev — October 26, 1962",
    date: "1962-10-26",
    classification: "TOP SECRET",
    source: "Cuban Government Archive (Declassified 1992)",
    content: "Dear Comrade Khrushchev,\n\nI believe the imperialists' aggressiveness is extremely dangerous and if they actually carry out the brutal act of invading Cuba, that would be the moment to eliminate such danger forever through an act of clear legitimate defense, however harsh and terrible the solution would be.\n\nI do not suggest, Comrade Khrushchev, that you take that step lightly. I only wish to convey my own judgment: the danger of a first strike by the enemy is real. If they invade Cuba, we are prepared to fight and die.\n\nThe Cuban people are willing to sacrifice themselves for the cause of socialism.\n\nFraternally,\nFidel Castro",
    analysis_prompt: "Castro appeared to advocate for a nuclear first strike. How does this reveal the tension between Cuba's sovereignty and Soviet control of the weapons? Who really controlled this crisis?",
    connections: ["doc_khrushchev_letter", "doc_khrushchev_fears", "doc_kennedy_address"],
    unlocks: ["doc_khrushchev_castro_rebuke"],
    tier: 3,
    perspective: "Cuban Leadership",
  },

  // === PROPAGANDA ===
  {
    id: "prop_us_poster_red_cuba",
    category: "propaganda",
    title: "US Poster: 'Red Shadow Over Cuba'",
    date: "1961-04-01",
    classification: "UNCLASSIFIED",
    source: "US Information Agency",
    content: "An American propaganda poster showing a giant red hand (representing Communism) gripping the island of Cuba. The shadow of the hand stretches across the Caribbean toward Florida and Latin America. Bold text reads: 'COMMUNISM IN OUR BACKYARD — WILL YOU LET IT SPREAD?'\n\nSmaller text urges citizens to support the Monroe Doctrine and 'the defense of Western Hemisphere freedom.' An American eagle stands guard at the Florida strait.",
    analysis_prompt: "What fears is this poster exploiting? How does framing Cuba as 'our backyard' reflect assumptions about US dominance in the Western Hemisphere?",
    connections: ["doc_monroe_doctrine", "doc_bay_of_pigs", "prop_soviet_poster_hands"],
    unlocks: [],
    tier: 1,
    perspective: "US Propaganda",
  },
  {
    id: "prop_soviet_poster_hands",
    category: "propaganda",
    title: "Soviet Poster: '¡Manos Fuera de Cuba!'",
    date: "1962-10-25",
    classification: "UNCLASSIFIED",
    source: "Soviet State Publishing",
    content: "A Soviet propaganda poster showing Uncle Sam's hands being slapped away from Cuba by the united fists of Cuban and Soviet workers. The Cuban flag waves proudly in the background beside the Soviet hammer and sickle. Text reads: '¡MANOS FUERA DE CUBA!' (Hands Off Cuba!)\n\nBelow: 'The peoples of the world stand with revolutionary Cuba against imperialist aggression.'",
    analysis_prompt: "Compare this with the American poster. How do both sides use visual metaphors of 'hands' to frame the conflict? Who is the aggressor in each narrative?",
    connections: ["prop_us_poster_red_cuba", "doc_pravda_blockade", "doc_kennedy_address"],
    unlocks: ["prop_cuban_literacy"],
    tier: 1,
    perspective: "Soviet Propaganda",
  },
  {
    id: "prop_cuban_literacy",
    category: "propaganda",
    title: "Cuban Poster: 'The Year of Education'",
    date: "1961-12-22",
    classification: "UNCLASSIFIED",
    source: "Cuban Ministry of Education",
    content: "A vibrant Cuban poster celebrating the 1961 Literacy Campaign. A young volunteer teacher holds a book in one hand and a lantern in the other, walking into a rural mountain village. Text reads: 'CUBA: Territory Free of Illiteracy!'\n\nFact sheet attached: The campaign sent 250,000 young volunteers into the countryside. Illiteracy dropped from 23.6% to 3.9% in one year. UNESCO recognized it as one of the most successful literacy campaigns in history.",
    analysis_prompt: "The literacy campaign was real and successful — but it was also powerful propaganda. How can something be both a genuine achievement and a political tool? Does this complicate the 'hero or dictator' question?",
    connections: ["doc_castro_speech_history", "doc_cuban_life_before_after", "civilian_teacher_account"],
    unlocks: ["doc_political_prisoners"],
    tier: 2,
    perspective: "Cuban Government",
  },

  // === INTELLIGENCE REPORTS ===
  {
    id: "doc_bay_of_pigs",
    category: "intelligence",
    title: "CIA After-Action Report: Bay of Pigs",
    date: "1961-06-13",
    classification: "TOP SECRET // EYES ONLY",
    source: "Central Intelligence Agency — Inspector General",
    content: "OPERATION ZAPATA — POST-MORTEM ANALYSIS\n\nThe operation to overthrow the Castro government via a brigade of Cuban exiles landed at the Bay of Pigs on April 17, 1961. The operation failed.\n\nKey failures:\n1. Air support was cancelled by the President at the last moment\n2. The landing site was poorly chosen — swamp terrain impeded movement\n3. The local population did NOT rise up against Castro as predicted\n4. Cuban military response was far faster and more organized than estimated\n5. Brigade 2506 was overwhelmed — 114 killed, 1,189 captured\n\nAssessment: The operation strengthened Castro domestically and drove Cuba firmly into the Soviet orbit. It validated Castro's warnings about American aggression.\n\nRECOMMENDATION: [REDACTED]",
    analysis_prompt: "The CIA admitted the invasion 'strengthened Castro.' How does a failed attack often empower the person it targets? What unintended consequences followed?",
    connections: ["doc_castro_speech_history", "doc_mongoose_ops", "photo_batista_palace"],
    unlocks: ["doc_mongoose_ops"],
    tier: 1,
    perspective: "US Intelligence",
  },
  {
    id: "doc_mongoose_ops",
    category: "intelligence",
    title: "Operation Mongoose: Covert Action Program",
    date: "1961-11-30",
    classification: "TOP SECRET // SENSITIVE",
    source: "CIA / Special Group (Augmented)",
    content: "OPERATION MONGOOSE — COVERT ACTION AGAINST CUBA\n\nObjective: Use all available means to overthrow the Communist regime in Cuba.\n\nApproved operations include:\n- Sabotage of Cuban sugar mills and oil refineries\n- Contamination of sugar exports\n- Destruction of bridges and railroad tracks\n- Psychological warfare operations\n- Support for internal resistance groups\n\nASSASSINATION PROPOSALS (not yet authorized):\n- Exploding cigar\n- Poisoned diving suit\n- Contaminated pen\n- Mafia cooperation for assassination\n\nNote: Attorney General Robert Kennedy is personally directing the operation. He has demanded 'more aggressive action.'",
    analysis_prompt: "The US government was actively trying to assassinate Castro and sabotage Cuba. How might knowledge of these operations have influenced Soviet decisions to arm Cuba?",
    connections: ["doc_bay_of_pigs", "doc_khrushchev_fears", "doc_castro_khrushchev_cable"],
    unlocks: ["doc_cuban_fear_invasion"],
    tier: 2,
    perspective: "US Intelligence",
  },
  {
    id: "doc_cia_castro_assessment",
    category: "intelligence",
    title: "CIA Assessment: Castro's Political Evolution",
    date: "1959-12-11",
    classification: "SECRET",
    source: "CIA Directorate of Intelligence",
    content: "SUBJECT: Assessment of Fidel Castro Ruz\n\nCastro's political orientation remains ambiguous. While he has not formally declared Marxist-Leninist ideology, several indicators suggest leftward drift:\n\n1. Land reform program nationalizes foreign-held estates\n2. Close association with Raúl Castro and Che Guevara (confirmed Marxists)\n3. Nationalization of American-owned properties accelerating\n4. Growing hostility toward US business interests\n\nHowever: Castro continues to deny Communist affiliation publicly. He has stated: 'I am not a Communist and neither is the revolutionary movement.'\n\nASSESSMENT: Castro may be a pragmatic nationalist who will align with whoever offers the best terms. If the US pushes too hard, we risk driving him directly to Moscow.\n\nRECOMMENDATION: Engagement may still be possible. [REDACTED]",
    analysis_prompt: "The CIA itself warned that pushing Castro too hard would drive him to Moscow. What happened? Did US policy create its own worst fear?",
    connections: ["doc_matthews_interview", "doc_us_embargo", "doc_soviet_aid_records"],
    unlocks: [],
    tier: 2,
    perspective: "US Intelligence",
  },

  // === SPEECHES ===
  {
    id: "doc_kennedy_address",
    category: "speeches",
    title: "Kennedy's Address to the Nation, Oct 22, 1962",
    date: "1962-10-22",
    classification: "UNCLASSIFIED",
    source: "White House Transcript",
    content: "Good evening, my fellow citizens.\n\nThis Government, as promised, has maintained the closest surveillance of the Soviet military build-up on the island of Cuba. Within the past week, unmistakable evidence has established the fact that a series of offensive missile sites is now in preparation on that imprisoned island.\n\nThe purpose of these bases can be none other than to provide a nuclear strike capability against the Western Hemisphere.\n\nI call upon Chairman Khrushchev to halt and eliminate this clandestine, reckless, and provocative threat to world peace.\n\nOur goal is not the victory of might, but the vindication of right — not peace at the expense of freedom, but both peace and freedom.\n\nGod willing, that goal will be achieved.",
    analysis_prompt: "Kennedy called Cuba 'that imprisoned island.' Who imprisoned it — Castro, the Soviets, or the US embargo? Notice how language shapes who the audience sees as the villain.",
    connections: ["photo_u2_missiles", "doc_pravda_blockade", "doc_khrushchev_letter"],
    unlocks: ["doc_excomm_transcript"],
    tier: 2,
    perspective: "US Leadership",
  },
  {
    id: "doc_castro_speech_history",
    category: "speeches",
    title: "Castro: 'History Will Absolve Me'",
    date: "1953-10-16",
    classification: "UNCLASSIFIED",
    source: "Court Transcript, Santiago de Cuba",
    content: "From Castro's defense speech after the failed Moncada Barracks attack:\n\n\"Cuba could easily provide for a population three times as great as it has now, so there is no excuse for the poverty of its people. The markets should be overflowing with produce, pantries should be full, every hand should have work...\n\nThe next revolutionary government will proceed to the comprehensive reform of our educational system...\n\nFive revolutionary laws would have been proclaimed immediately after the capture of the Moncada barracks:\n1. Restoration of the Constitution\n2. Land reform\n3. Workers' share of profits\n4. Sugar planters' share of the crop\n5. Confiscation of corrupt officials' assets\n\nCondemn me. It does not matter. History will absolve me.\"",
    analysis_prompt: "These early promises sound democratic and egalitarian. Which were kept? Which were broken? Does the path from idealist to authoritarian leader follow a pattern?",
    connections: ["photo_sierra_maestra", "doc_matthews_interview", "doc_land_reform"],
    unlocks: [],
    tier: 1,
    perspective: "Cuban Revolutionary",
  },

  // === CIVILIAN ACCOUNTS ===
  {
    id: "civilian_havana_1962",
    category: "civilian",
    title: "María Gonzalez — Havana Housewife, October 1962",
    date: "1962-10-24",
    classification: "DECLASSIFIED",
    source: "Oral History Project, University of Havana (1998)",
    content: "\"We didn't know about the missiles. Nobody told us. One day, everything was normal. The next day, the whole neighborhood was digging trenches. The Committee for the Defense of the Revolution came to our building and said, 'The Yankees are about to invade.'\n\nMy husband wanted to fight. I just wanted to find milk for the baby. The stores were empty. We couldn't leave the city. There were soldiers everywhere.\n\nI remember thinking: we're going to die, and we don't even know why. Later, I learned about the missiles. Nobody asked us if we wanted them. Not Castro. Not Khrushchev. Not Kennedy. The three most powerful men on Earth were gambling with our lives, and we were invisible.\"",
    analysis_prompt: "María says she was 'invisible.' How often are civilian perspectives missing from Cold War history? Whose voices are usually heard?",
    connections: ["doc_cuban_life_before_after", "doc_kennedy_address", "doc_castro_khrushchev_cable"],
    unlocks: ["civilian_teacher_account"],
    tier: 2,
    perspective: "Cuban Civilian",
  },
  {
    id: "civilian_teacher_account",
    category: "civilian",
    title: "Elena Vásquez — Literacy Campaign Volunteer, 1961",
    date: "1961-08-15",
    classification: "UNCLASSIFIED",
    source: "Oral History Project, University of Havana (1998)",
    content: "\"I was fifteen years old. They gave me a lantern and a primer and sent me to the mountains. The farmers could not read their own names.\n\nI taught an old man named Tomás. He was sixty years old and had never held a pencil. When he finally wrote his name — 'Tomás' — he cried. I cried too.\n\nWas I being used by the revolution? Maybe. But Tomás could read. That was real. When people tell me the revolution was all bad, I think of Tomás. When they tell me it was all good, I think of my cousin who was arrested for criticizing Castro and spent three years in prison.\n\nThe truth is complicated.\"",
    analysis_prompt: "Elena captures the central tension of revolutionary Cuba: genuine achievements alongside political repression. How do we judge a system that teaches people to read but imprisons people who speak freely?",
    connections: ["prop_cuban_literacy", "doc_political_prisoners", "doc_cuban_life_before_after"],
    unlocks: [],
    tier: 2,
    perspective: "Cuban Civilian",
  },
  {
    id: "civilian_exile_miami",
    category: "civilian",
    title: "Roberto Fernández — Cuban Exile, Miami, 1965",
    date: "1965-03-20",
    classification: "UNCLASSIFIED",
    source: "Miami Herald Oral History Collection",
    content: "\"My family owned a small printing shop in Havana for thirty years. In 1960, they nationalized everything. No compensation. No warning. Soldiers came with papers and told us, 'This belongs to the people now.'\n\nWe left with two suitcases and my mother's rosary. I was seventeen. My father never recovered. He died in Miami two years later — of a broken heart, my mother said.\n\nPeople say Batista was bad, and he was. But under Batista, we had our shop. Under Castro, we had nothing. Some revolutions just change who does the stealing.\n\nI still dream in Spanish about streets I'll never walk again.\"",
    analysis_prompt: "Roberto lost everything to nationalization. Compare his experience with the literacy campaign. Can a revolution be liberating for some and devastating for others simultaneously?",
    connections: ["doc_land_reform", "doc_us_embargo", "civilian_teacher_account"],
    unlocks: [],
    tier: 2,
    perspective: "Cuban Exile",
  },

  // === ECONOMIC RECORDS ===
  {
    id: "doc_sugar_trade",
    category: "economic",
    title: "Cuba-US Sugar Trade Data, 1950-1961",
    date: "1961-12-01",
    classification: "UNCLASSIFIED",
    source: "US Department of Commerce",
    content: "CUBA-US SUGAR TRADE STATISTICS\n\n1950: Cuba supplies 33% of all US sugar imports\n1955: 58% of Cuban farmland owned by US companies\n1958: Sugar accounts for 80% of Cuban export revenue\n1959: Castro begins land reform — US-owned estates seized\n1960: US reduces Cuban sugar quota by 95%\n1961: Full US trade embargo imposed\n\nImpact: Cuba lost its primary export market overnight. Sugar that once went to American tables now had nowhere to go. Within months, Cuba negotiated emergency trade agreements with the Soviet Union.\n\nThe embargo was intended to strangle the Castro regime. Instead, it pushed Cuba directly into Soviet economic dependency.",
    analysis_prompt: "The US controlled 58% of Cuban farmland and bought most of Cuba's sugar. When Cuba nationalized these holdings, the US imposed an embargo. Who was punishing whom — and who suffered most?",
    connections: ["photo_batista_palace", "doc_us_embargo", "doc_soviet_aid_records"],
    unlocks: ["doc_cuban_life_before_after"],
    tier: 1,
    perspective: "Economic",
  },
  {
    id: "doc_us_embargo",
    category: "economic",
    title: "Executive Order: Trade Embargo on Cuba",
    date: "1962-02-03",
    classification: "UNCLASSIFIED",
    source: "White House / Federal Register",
    content: "PROCLAMATION 3447 — EMBARGO ON ALL TRADE WITH CUBA\n\nWHEREAS the United States, in accordance with its international obligations, is prepared to take all necessary actions to promote national and hemispheric security;\n\nNOW, THEREFORE, I, JOHN F. KENNEDY, President of the United States, do hereby proclaim that all imports of goods of Cuban origin are prohibited. All exports of goods to Cuba are prohibited.\n\nThe embargo extends to: food, medicine, machinery, fuel, consumer goods, and all forms of economic exchange.\n\nPurpose: To deny the Castro regime the resources necessary to maintain its grip on power.\n\nPenalties: Violations punishable by fines up to $10,000 and imprisonment up to 10 years.",
    analysis_prompt: "The embargo included food and medicine. If the goal was to weaken Castro, who actually suffered? Is it ethical to punish an entire population for the actions of their government?",
    connections: ["doc_sugar_trade", "doc_cuban_life_before_after", "doc_soviet_aid_records"],
    unlocks: [],
    tier: 1,
    perspective: "US Government",
  },
  {
    id: "doc_soviet_aid_records",
    category: "economic",
    title: "Soviet Economic Aid to Cuba, 1960-1965",
    date: "1965-06-01",
    classification: "SECRET",
    source: "CIA Economic Intelligence Report",
    content: "SOVIET AID TO CUBA — CLASSIFIED ASSESSMENT\n\n1960: USSR agrees to purchase 1 million tons of Cuban sugar annually\n1961: Soviet economic aid reaches $100 million annually\n1962: Military aid valued at estimated $500 million\n1963: Total Soviet subsidy exceeds $1 million per day\n\nThe USSR buys Cuban sugar at above-market prices and provides oil, machinery, and consumer goods at subsidized rates. Cuba has become the most expensive Soviet client state.\n\nAssessment: Cuba is now economically dependent on the Soviet Union in the same way it was once dependent on the United States. Cuba has traded one patron for another.\n\nIMPLICATION: The embargo succeeded in cutting US-Cuba ties but failed to isolate Cuba. It merely redirected Cuba's dependency.",
    analysis_prompt: "Cuba went from US economic dependency to Soviet dependency. Did Cuba ever achieve true independence? What does this pattern reveal about Cold War power dynamics?",
    connections: ["doc_sugar_trade", "doc_us_embargo", "doc_khrushchev_fears"],
    unlocks: [],
    tier: 2,
    perspective: "US Intelligence",
  },

  // === INTERCEPTED COMMUNICATIONS ===
  {
    id: "doc_excomm_transcript",
    category: "communications",
    title: "ExComm Meeting Transcript — October 16, 1962",
    date: "1962-10-16",
    classification: "TOP SECRET",
    source: "White House Recording System (Declassified 1997)",
    content: "EXECUTIVE COMMITTEE OF THE NATIONAL SECURITY COUNCIL\nOctober 16, 1962 — 11:50 AM\n\nGENERAL TAYLOR: We have confirmed Soviet MRBMs in Cuba. They will be operational within two weeks.\n\nSECRETARY McNAMARA: We have three options: diplomatic pressure, a naval blockade, or a full air strike.\n\nATTORNEY GENERAL KENNEDY: An air strike on Cuba would be a 'Pearl Harbor in reverse.' I don't think that's who we are.\n\nGENERAL LeMay: Mr. President, this is almost as bad as the appeasement at Munich. We should strike now, hard.\n\nPRESIDENT KENNEDY: If we attack Cuba, the Soviets will take Berlin. Then what do we do? Attack them there too?\n\nSECRETARY RUSK: The blockade gives Khrushchev time to think. An air strike gives him only the option to react.\n\nPRESIDENT KENNEDY: Let's pursue the blockade option. But call it a 'quarantine.' A blockade is an act of war.",
    analysis_prompt: "Notice how different advisors pushed for different actions. Kennedy chose the blockade partly because an air strike felt morally wrong AND strategically dangerous. How often do moral instincts align with strategic wisdom?",
    connections: ["doc_kennedy_address", "map_missile_range", "doc_khrushchev_letter"],
    unlocks: ["doc_defcon_records"],
    tier: 3,
    perspective: "US Leadership",
  },

  // === HIDDEN / UNLOCKABLE DOCUMENTS ===
  {
    id: "doc_turkey_missiles",
    category: "intelligence",
    title: "Jupiter Missiles in Turkey — Background Brief",
    date: "1962-01-15",
    classification: "SECRET",
    source: "Department of State",
    content: "BACKGROUND: In 1961, the United States deployed 15 Jupiter intermediate-range ballistic missiles in Turkey, within striking distance of Moscow. These missiles were part of NATO's forward defense strategy.\n\nKhrushchev reportedly told his son: 'Americans have surrounded us with bases. In Turkey, in Italy, in Germany. Why should we not have a base in Cuba? What's the difference?'\n\nThe Jupiter missiles were already considered obsolete by 1962. However, their removal had not been ordered due to political symbolism and alliance management concerns.\n\nNOTE: The existence of a secret deal to remove these missiles was denied by the Kennedy administration for decades.",
    analysis_prompt: "The US had missiles in Turkey first. Khrushchev's response was to put missiles in Cuba. Does knowing this change who you see as the 'aggressor'? Why was this fact hidden from the public?",
    connections: ["map_turkey_missiles", "doc_khrushchev_letter", "doc_secret_negotiations"],
    unlocks: [],
    tier: 2,
    perspective: "US/Soviet Strategic",
  },
  {
    id: "doc_secret_negotiations",
    category: "intelligence",
    title: "The Secret Deal — Bobby Kennedy & Dobrynin",
    date: "1962-10-27",
    classification: "TOP SECRET // SENSITIVE",
    source: "Declassified State Department Records (1989)",
    content: "MEMORANDUM OF CONVERSATION\nOctober 27, 1962 — Soviet Embassy, Washington\n\nAttorney General Robert Kennedy met secretly with Ambassador Dobrynin. Kennedy conveyed:\n\n1. The US will publicly pledge not to invade Cuba\n2. The US will SECRETLY remove Jupiter missiles from Turkey within 4-5 months\n3. The Turkey arrangement must remain secret — if leaked, the deal is off\n\nDobrynin relayed this to Moscow. Khrushchev accepted.\n\nThe crisis was resolved. But the public was told only about the non-invasion pledge. The Turkey missile removal was hidden for over 25 years.\n\nWhy the secrecy? Kennedy feared appearing weak — trading away NATO assets under Soviet pressure. The official narrative became: Khrushchev blinked. Kennedy stood firm.\n\nThe reality was more nuanced: both sides compromised.",
    analysis_prompt: "The 'official story' was that Kennedy won and Khrushchev backed down. The truth was a secret compromise. How does this change the narrative of the Cuban Missile Crisis? Why do governments control historical narratives?",
    connections: ["doc_khrushchev_letter", "doc_bobby_kennedy_backchannel", "map_turkey_missiles"],
    unlocks: [],
    tier: 3,
    perspective: "US/Soviet Diplomatic",
  },
  {
    id: "doc_bobby_kennedy_backchannel",
    category: "telegrams",
    title: "Bobby Kennedy's Secret Backchannel Notes",
    date: "1962-10-27",
    classification: "TOP SECRET",
    source: "Robert F. Kennedy Papers (Declassified 2001)",
    content: "Personal notes by Robert Kennedy:\n\n'I told Dobrynin that the President was under enormous pressure from the military to bomb Cuba. The hawks want war. The President does not. But if we cannot resolve this in 24-48 hours, the President may lose control of the situation.\n\nI emphasized: this is not a threat. This is reality. There are people in this government who WANT this war.\n\nDobrynin looked shaken. He asked about Turkey. I said: the missiles there are already obsolete. They will be removed quietly. But this cannot be public.\n\nWe shook hands. I thought: this handshake might save the world.'",
    analysis_prompt: "Bobby Kennedy used the real threat of military hawks to pressure the Soviets. Was this honest negotiation or manipulation? And can the same action be both?",
    connections: ["doc_secret_negotiations", "doc_excomm_transcript", "doc_khrushchev_letter"],
    unlocks: [],
    tier: 3,
    perspective: "US Leadership",
  },
  {
    id: "doc_khrushchev_fears",
    category: "intelligence",
    title: "CIA Profile: Khrushchev's Strategic Anxieties",
    date: "1962-08-01",
    classification: "SECRET",
    source: "CIA Directorate of Intelligence",
    content: "PSYCHOLOGICAL PROFILE: NIKITA KHRUSHCHEV\n\nKey anxieties driving Soviet policy:\n\n1. MISSILE GAP: The US has a 17:1 advantage in nuclear warheads. Khrushchev knows the Soviet Union cannot win an arms race.\n\n2. ENCIRCLEMENT: US bases surround the USSR — Turkey, Italy, UK, Japan, South Korea. Cuba represents the ONLY potential Soviet forward position.\n\n3. BERLIN: Khrushchev has failed to resolve the Berlin question. Cuba could provide leverage.\n\n4. CHINA: Mao is criticizing Khrushchev as weak. Defending Cuba proves Soviet commitment to global communism.\n\n5. BAY OF PIGS: If the US invaded once, they'll invade again. Khrushchev feels personally obligated to protect Castro.\n\nASSESSMENT: Khrushchev is not irrational. His actions follow a defensive logic — but one that could lead to catastrophic miscalculation.",
    analysis_prompt: "The CIA understood Khrushchev's motivations were defensive, not aggressive. Yet publicly, the US portrayed Soviet actions as unprovoked aggression. Why the disconnect between intelligence and public narrative?",
    connections: ["doc_khrushchev_letter", "doc_mongoose_ops", "doc_turkey_missiles", "photo_missile_parade"],
    unlocks: [],
    tier: 2,
    perspective: "US Intelligence",
  },
  {
    id: "doc_defcon_records",
    category: "communications",
    title: "DEFCON 2 — Strategic Air Command Records",
    date: "1962-10-24",
    classification: "TOP SECRET",
    source: "US Strategic Air Command",
    content: "241400Z OCT 62\n\nFROM: CINCSAC\nTO: ALL SAC UNITS\n\nSET DEFCON 2. REPEAT. DEFCON 2.\n\nThis is the first time in history SAC has been at DEFCON 2.\n\nAll B-52 bombers airborne with nuclear weapons. 24-hour alert rotation.\n182 ICBMs fueled and targeted.\nPolaris submarines at launch positions.\n\nEstimated destruction if exchange occurs:\n- US casualties: 60-80 million in first hour\n- Soviet casualties: 100-120 million in first hour\n- Fallout casualties worldwide: unknown but potentially billions\n\nNote: At DEFCON 2, a single miscommunication could trigger launch. Multiple 'false alarm' incidents have already occurred this week.\n\nThe margin between civilization and annihilation is now measured in minutes.",
    analysis_prompt: "The world was one miscommunication away from nuclear war. What does it mean that 'false alarm incidents' were already happening? How much of survival came down to luck?",
    connections: ["doc_excomm_transcript", "map_missile_range", "doc_kennedy_address"],
    unlocks: [],
    tier: 3,
    perspective: "US Military",
  },
  {
    id: "doc_cuban_life_before_after",
    category: "economic",
    title: "Cuba: Life Before and After the Revolution",
    date: "1965-01-01",
    classification: "UNCLASSIFIED",
    source: "UNESCO / World Bank Comparative Data",
    content: "COMPARATIVE DATA: CUBA PRE-REVOLUTION vs POST-REVOLUTION\n\nBEFORE (1958):\n- Literacy rate: 76.4%\n- Infant mortality: 32 per 1,000\n- Doctors per capita: 1 per 1,000\n- 75% of rural homes had no running water\n- 44% of rural population never attended school\n- Unemployment: 25% (seasonal agricultural workers)\n- Per capita income ranked 3rd in Latin America\n\nAFTER (1965):\n- Literacy rate: 96.1%\n- Infant mortality: 22 per 1,000\n- Doctors per capita: 1.2 per 1,000 (free healthcare)\n- Universal education implemented\n- Unemployment virtually eliminated\n- Per capita income fell to 8th in Latin America\n- Political prisoners: estimated 15,000-20,000\n- Press freedom: eliminated\n- Free elections: none held\n\nAssessment: The revolution dramatically improved health and education but at severe cost to political freedoms and economic growth.",
    analysis_prompt: "How do you weigh literacy and healthcare against political imprisonment and censorship? Is there a 'correct' answer, or does it depend on who you ask?",
    connections: ["doc_sugar_trade", "prop_cuban_literacy", "doc_political_prisoners"],
    unlocks: [],
    tier: 2,
    perspective: "International",
  },
  {
    id: "doc_political_prisoners",
    category: "civilian",
    title: "Amnesty International: Political Prisoners in Cuba",
    date: "1964-09-01",
    classification: "UNCLASSIFIED",
    source: "Amnesty International Report",
    content: "POLITICAL IMPRISONMENT IN REVOLUTIONARY CUBA\n\nEstimated political prisoners: 15,000-20,000\n\nCategories include:\n- Former Batista officials and military officers\n- Independent journalists\n- Labor union leaders who opposed state control\n- Religious leaders (particularly Jehovah's Witnesses)\n- Homosexuals (sent to UMAP forced labor camps 1965-1968)\n- Suspected CIA collaborators\n- Cubans who attempted unauthorized emigration\n\nConditions: Overcrowding, limited food, forced labor in sugar fields. Reports of solitary confinement and psychological pressure.\n\nContext: Castro justified imprisonment as necessary defense against US-backed counterrevolution. Critics argue the scope far exceeded any legitimate security need.\n\nNote: Many democratic nations allied with the US (including South Vietnam and several Latin American dictatorships) had equal or worse human rights records during this period.",
    analysis_prompt: "The report notes US allies had similar or worse records. Does that context matter? Is it whataboutism, or is it important for understanding Cold War moral complexity?",
    connections: ["doc_cuban_life_before_after", "civilian_exile_miami", "prop_cuban_literacy"],
    unlocks: [],
    tier: 3,
    perspective: "International",
  },
  {
    id: "doc_land_reform",
    category: "economic",
    title: "Cuban Land Reform Act of 1959",
    date: "1959-05-17",
    classification: "UNCLASSIFIED",
    source: "Cuban Government Gazette",
    content: "AGRARIAN REFORM LAW — KEY PROVISIONS\n\n1. No individual may own more than 402 hectares of land\n2. Excess lands to be redistributed to landless peasants\n3. Foreign ownership of Cuban agricultural land is prohibited\n4. Affected: United Fruit Company, King Ranch, and other US corporations\n5. Compensation offered in 20-year bonds (rejected by US companies)\n\nIMPACT:\n- 200,000 peasant families received land\n- US corporate losses estimated at $1.8 billion\n- US government called the law 'confiscatory'\n- Eisenhower administration began planning regime change\n\nCuban perspective: 'We are simply reclaiming what was always ours.'\nUS perspective: 'This is theft of American property.'",
    analysis_prompt: "Land reform gave land to 200,000 families but enraged the US. At what point does a country's right to manage its own resources conflict with foreign property rights? Who decides?",
    connections: ["doc_sugar_trade", "doc_castro_speech_history", "civilian_exile_miami"],
    unlocks: [],
    tier: 1,
    perspective: "Cuban Government",
  },
  {
    id: "doc_mafia_havana",
    category: "intelligence",
    title: "FBI Report: The Mafia in Pre-Revolution Havana",
    date: "1958-06-01",
    classification: "CONFIDENTIAL",
    source: "Federal Bureau of Investigation",
    content: "ORGANIZED CRIME OPERATIONS IN HAVANA, CUBA\n\nThe Batista government has allowed American organized crime figures to operate openly in Cuba:\n\n- Meyer Lansky controls the Hotel Nacional casino\n- Santos Trafficante operates the Sans Souci nightclub\n- Lucky Luciano maintains interests through intermediaries\n\nEstimated annual revenue from Havana gambling: $100 million\nEstimated bribes to Batista officials: $10-15 million annually\n\nHavana has become 'the Latin Las Vegas' — a playground for wealthy Americans. Prostitution, drugs, and gambling operate without restriction.\n\nContrast: Average Cuban agricultural worker earns $91/year.\n\nNote: The CIA later approached Mafia figures for assistance in assassinating Castro.",
    analysis_prompt: "The US-backed government allowed the American Mafia to run Havana while Cuban workers earned $91/year. Does this context affect how you view the revolution that followed?",
    connections: ["photo_batista_palace", "doc_mongoose_ops", "doc_batista_economy"],
    unlocks: [],
    tier: 2,
    perspective: "US Law Enforcement",
  },
  {
    id: "doc_batista_economy",
    category: "economic",
    title: "Economic Profile: Cuba Under Batista, 1958",
    date: "1958-12-01",
    classification: "UNCLASSIFIED",
    source: "World Bank Economic Survey",
    content: "ECONOMIC PROFILE: REPUBLIC OF CUBA, 1958\n\nGDP per capita: $353 (3rd highest in Latin America)\nHowever, wealth distribution is extremely unequal:\n- Top 10% control 39% of national income\n- Bottom 40% control 6.5% of national income\n- Rural poverty rate: estimated 60%\n\nForeign ownership:\n- 40% of sugar production: US-owned\n- 90% of telephone/electric services: US-owned\n- 50% of railways: US-owned\n- 25% of bank deposits: US-owned\n\nLabor conditions:\n- Sugar workers employed only 4 months/year\n- No unemployment insurance\n- Limited labor rights\n\nAssessment: Cuba is wealthy on paper but deeply unequal. The conditions for revolutionary upheaval are present.",
    analysis_prompt: "Cuba ranked 3rd in Latin American GDP but had 60% rural poverty. What does GDP actually tell us about a country? How can a nation be 'rich' and 'poor' simultaneously?",
    connections: ["photo_batista_palace", "doc_sugar_trade", "doc_land_reform"],
    unlocks: [],
    tier: 1,
    perspective: "International",
  },
  {
    id: "doc_cuban_fear_invasion",
    category: "civilian",
    title: "Cuban Military Preparations — Civilian Mobilization",
    date: "1962-10-23",
    classification: "DECLASSIFIED",
    source: "Cuban Revolutionary Armed Forces Archive",
    content: "ORDER: FULL MOBILIZATION\n\n270,000 regular military forces deployed\n100,000 militia activated\nCivilian defense committees organized block by block\n\nExpected US invasion force: 180,000 troops\n\nCastro's order to the people:\n'Every man, woman, and child who can hold a weapon will defend the Revolution. We will fight in the streets, in the mountains, in the cane fields. Cuba will not surrender.'\n\nSoviet tactical nuclear weapons on Cuban soil: 98 warheads\nSoviet field commanders had authority to use tactical nukes if invaded\n\nNOTE: Kennedy did not know about the tactical nuclear weapons. If the US had invaded, Soviet commanders in Cuba could have launched nuclear weapons WITHOUT Moscow's approval.\n\nThis information was not revealed until 1992.",
    analysis_prompt: "Soviet field commanders could launch nuclear weapons without Moscow's permission. Kennedy didn't know this. What does this reveal about how close the world actually came to nuclear war?",
    connections: ["doc_mongoose_ops", "doc_defcon_records", "civilian_havana_1962"],
    unlocks: [],
    tier: 3,
    perspective: "Cuban/Soviet Military",
  },
  {
    id: "doc_khrushchev_castro_rebuke",
    category: "telegrams",
    title: "Khrushchev's Reply to Castro's 'First Strike' Cable",
    date: "1962-10-30",
    classification: "TOP SECRET",
    source: "Soviet Archive (Declassified 1992)",
    content: "Dear Comrade Fidel,\n\nI have received your letter. We understand your feelings of indignation.\n\nHowever, I must be frank with you: had we agreed with your proposal, which you made at the peak of the crisis, it would have led not simply to a strike against Cuba, but to a full thermonuclear world war.\n\nDear Comrade Fidel, I consider this proposal of yours as incorrect, even though I understand your motivation.\n\nWe are not struggling against imperialism in order to die. We want to win. And for that, we must live.\n\nWe pulled the world back from the brink. History will understand this.\n\nN. Khrushchev",
    analysis_prompt: "Khrushchev essentially told Castro: 'Your suggestion would have ended civilization.' How does this exchange reveal who actually held power in this relationship? Was Cuba a partner or a pawn?",
    connections: ["doc_castro_khrushchev_cable", "doc_secret_negotiations"],
    unlocks: [],
    tier: 3,
    perspective: "Soviet Leadership",
  },
  {
    id: "doc_arms_race_data",
    category: "economic",
    title: "Nuclear Arsenal Comparison, 1962",
    date: "1962-10-01",
    classification: "SECRET",
    source: "CIA National Intelligence Estimate",
    content: "NUCLEAR FORCES COMPARISON — OCTOBER 1962\n\nUNITED STATES:\n- ICBMs: 203\n- SLBMs: 144\n- Strategic Bombers: 1,306\n- Total warheads: ~27,000\n\nSOVIET UNION:\n- ICBMs: 36\n- SLBMs: 72\n- Strategic Bombers: 138\n- Total warheads: ~3,322\n\nUS advantage: approximately 8:1\n\nKhrushchev's problem: The Soviet Union cannot match US production. Placing missiles in Cuba is a SHORTCUT — it eliminates the need for expensive ICBMs by using cheaper medium-range missiles at close range.\n\nIn strategic terms: Cuba transformed the Soviet Union from a distant threat into a next-door threat overnight.",
    analysis_prompt: "The US had 8 times more nuclear weapons. Yet Americans felt terrified by Soviet missiles in Cuba. How does geography change the psychology of threat, even when the raw numbers favor you?",
    connections: ["photo_missile_parade", "map_missile_range", "doc_khrushchev_fears"],
    unlocks: [],
    tier: 2,
    perspective: "US Intelligence",
  },
  {
    id: "doc_monroe_doctrine",
    category: "speeches",
    title: "The Monroe Doctrine and Cuba",
    date: "1962-09-01",
    classification: "UNCLASSIFIED",
    source: "US State Department Historical Office",
    content: "THE MONROE DOCTRINE — BACKGROUND\n\nIn 1823, President James Monroe declared that the Western Hemisphere was closed to further European colonization and that any attempt by a European power to extend its influence would be viewed as a hostile act against the United States.\n\nFor 139 years, this doctrine has been the foundation of US foreign policy in the Americas.\n\nApplication to Cuba, 1962:\nThe Kennedy administration invoked the Monroe Doctrine to justify the blockade. Soviet missiles in Cuba were framed as 'foreign power' intrusion into 'our hemisphere.'\n\nCritique: Latin American nations have long argued that the Monroe Doctrine is simply a justification for US imperialism — a claim that the entire Western Hemisphere is America's 'sphere of influence.'\n\nQuestion: Does a doctrine written in 1823 justify controlling what happens in another sovereign nation in 1962?",
    analysis_prompt: "The Monroe Doctrine essentially claimed the entire Western Hemisphere as a US zone of control. How does this 140-year-old policy connect to the Bay of Pigs, the embargo, and the missile crisis?",
    connections: ["prop_us_poster_red_cuba", "doc_bay_of_pigs", "doc_kennedy_address"],
    unlocks: [],
    tier: 1,
    perspective: "Historical",
  },
  {
    id: "doc_soviet_un_response",
    category: "speeches",
    title: "Soviet UN Address: 'American Hypocrisy'",
    date: "1962-10-25",
    classification: "UNCLASSIFIED",
    source: "United Nations General Assembly Record",
    content: "From Soviet Ambassador Zorin's address to the UN Security Council:\n\n'The United States, which maintains military bases in 36 countries, which has missiles pointed at the Soviet Union from Turkey, Italy, and the United Kingdom, now demands that the Soviet Union may not assist in the defense of a small island nation 90 miles from American shores.\n\nThis is not security. This is hypocrisy.\n\nWhen American missiles sit on our borders, it is called 'defense.' When Soviet missiles sit near American borders, it is called 'aggression.' The only difference is who holds the power to define these words.\n\nWe ask the Assembly: by what right does one nation claim an entire hemisphere as its exclusive domain?'",
    analysis_prompt: "Zorin calls out a double standard. Is he right? The US had missiles in Turkey but objected to Soviet missiles in Cuba. How do powerful nations justify applying different rules to themselves versus others?",
    connections: ["doc_pravda_blockade", "doc_turkey_missiles", "doc_monroe_doctrine"],
    unlocks: [],
    tier: 2,
    perspective: "Soviet Diplomatic",
  },
  {
    id: "doc_us_reaction_revolution",
    category: "intelligence",
    title: "State Department Memo: Response to Cuban Revolution",
    date: "1959-02-15",
    classification: "CONFIDENTIAL",
    source: "US Department of State",
    content: "MEMORANDUM: US POLICY OPTIONS REGARDING CUBA\n\nCastro has seized power. Batista has fled. The new government is popular but unpredictable.\n\nOPTION A: Engage with Castro. Offer economic incentives to prevent Soviet alignment. Risk: legitimizes revolutionary movements across Latin America.\n\nOPTION B: Isolate Castro. Economic pressure to force regime change. Risk: pushes Cuba toward the Soviet Union.\n\nOPTION C: Covert regime change. Train Cuban exiles for military operation. Risk: international backlash if exposed.\n\nRECOMMENDATION: A combination of B and C is recommended.\n\nNOTE: Several officials argued for Option A, warning that hostility would become a self-fulfilling prophecy. They were overruled.",
    analysis_prompt: "Option A (engagement) was rejected. Options B and C (hostility) were chosen. The CIA's own assessment warned this would push Cuba to Moscow. What drives governments to choose confrontation over diplomacy?",
    connections: ["doc_cia_castro_assessment", "doc_bay_of_pigs", "doc_us_embargo"],
    unlocks: [],
    tier: 2,
    perspective: "US Government",
  },
  {
    id: "doc_khrushchev_memoirs",
    category: "speeches",
    title: "Khrushchev Remembers — Memoir Excerpt",
    date: "1970-01-01",
    classification: "UNCLASSIFIED",
    source: "Published Memoirs (1970)",
    content: "From Khrushchev's memoirs, published after his removal from power:\n\n'The Americans had surrounded our country with military bases and now they would learn what it feels like to have enemy missiles pointed at them.\n\nWe had to help Cuba. It was not just about Castro — it was about showing the world that socialism could be defended. If we abandoned Cuba, who would trust us?\n\nBut when the crisis came, I realized: if we don't find a way out, we'll all be destroyed. I am not a man who fears death, but I am not a fool either. The missiles were not worth the end of civilization.\n\nIn the end, Kennedy and I both understood: neither of us wanted to be the last leader of our respective countries.'",
    analysis_prompt: "Khrushchev admits the missiles were partly about proving Soviet strength globally, not just defending Cuba. How does ego and reputation drive nations toward dangerous decisions?",
    connections: ["doc_khrushchev_fears", "map_turkey_missiles", "doc_secret_negotiations"],
    unlocks: [],
    tier: 3,
    perspective: "Soviet Leadership",
  },
];

// Define all possible connections for the evidence board
export const BOARD_CONNECTIONS = [
  { from: "doc_bay_of_pigs", to: "photo_u2_missiles", label: "Failed invasion → Soviet missile deployment", explanation: "The Bay of Pigs failure convinced Khrushchev that Cuba needed military protection and that the US would try again." },
  { from: "doc_us_embargo", to: "doc_soviet_aid_records", label: "US cuts trade → USSR fills the gap", explanation: "When the US cut all trade with Cuba, the Soviet Union stepped in as Cuba's new economic patron." },
  { from: "doc_turkey_missiles", to: "doc_khrushchev_fears", label: "US missiles near USSR → Soviet anxiety", explanation: "American Jupiter missiles in Turkey created a sense of strategic encirclement that motivated Khrushchev's Cuba gambit." },
  { from: "photo_batista_palace", to: "doc_castro_speech_history", label: "Batista's corruption → revolutionary movement", explanation: "The extreme inequality and corruption under Batista created the conditions that fueled Castro's revolution." },
  { from: "doc_sugar_trade", to: "doc_land_reform", label: "US sugar dominance → nationalization", explanation: "American corporations controlled most of Cuba's farmland, making land reform a direct challenge to US interests." },
  { from: "doc_mongoose_ops", to: "doc_cuban_fear_invasion", label: "CIA sabotage → Cuban mobilization", explanation: "Knowledge of Operation Mongoose confirmed Cuban fears that the US was actively trying to destroy the revolution." },
  { from: "doc_kennedy_address", to: "doc_pravda_blockade", label: "Kennedy's speech → Soviet counter-narrative", explanation: "Each side immediately framed the crisis to make the other appear as the aggressor." },
  { from: "doc_khrushchev_letter", to: "doc_secret_negotiations", label: "Khrushchev's plea → secret compromise", explanation: "Khrushchev's emotional letter led to the secret backchannel deal that resolved the crisis." },
  { from: "doc_castro_khrushchev_cable", to: "doc_khrushchev_castro_rebuke", label: "Castro's 'first strike' → Khrushchev's horror", explanation: "Castro appeared to advocate nuclear war; Khrushchev was appalled and this accelerated the secret deal." },
  { from: "prop_us_poster_red_cuba", to: "prop_soviet_poster_hands", label: "Competing propaganda narratives", explanation: "Both sides used remarkably similar visual techniques — hands, shadows, flags — to frame the other as the aggressor." },
  { from: "doc_cuban_life_before_after", to: "doc_political_prisoners", label: "Social gains vs political repression", explanation: "Cuba's revolution delivered real improvements in health and education but at severe cost to civil liberties." },
  { from: "doc_cia_castro_assessment", to: "doc_us_reaction_revolution", label: "CIA warned engagement, government chose hostility", explanation: "The intelligence community recognized the risk of pushing Castro to Moscow, but policymakers chose confrontation." },
  { from: "doc_batista_economy", to: "doc_mafia_havana", label: "Economic inequality enabled organized crime", explanation: "Batista's corrupt regime allowed the American Mafia to operate openly while most Cubans lived in poverty." },
  { from: "doc_arms_race_data", to: "map_missile_range", label: "Missile gap → Cuba as shortcut", explanation: "Facing an 8:1 nuclear disadvantage, the USSR used Cuba to cheaply close the strategic gap." },
  { from: "doc_monroe_doctrine", to: "doc_bay_of_pigs", label: "Hemisphere doctrine → regime change", explanation: "The Monroe Doctrine's claim over the Western Hemisphere provided ideological justification for the invasion." },
  { from: "civilian_havana_1962", to: "doc_cuban_fear_invasion", label: "Civilians caught in superpower chess", explanation: "Ordinary Cubans had no say in the crisis — their lives were gambled by leaders in Washington, Moscow, and Havana." },
  { from: "doc_excomm_transcript", to: "doc_defcon_records", label: "Debate leads to near-nuclear war", explanation: "While leaders debated, the military machine was already at DEFCON 2 — one step from nuclear launch." },
  { from: "prop_cuban_literacy", to: "doc_political_prisoners", label: "Achievement used to mask repression", explanation: "Genuine accomplishments like the literacy campaign coexisted with systematic political imprisonment." },
  { from: "civilian_teacher_account", to: "civilian_exile_miami", label: "Two Cuban experiences — same revolution", explanation: "The revolution was liberation for some and devastation for others, depending on class and politics." },
  { from: "doc_land_reform", to: "civilian_exile_miami", label: "Reform for peasants, loss for property owners", explanation: "Land redistribution gave to the landless but took from those who had — fueling the exile community." },
];

// Timeline events for reconstruction game
export const TIMELINE_EVENTS = [
  { id: "tl_batista_coup", date: "1952-03-10", title: "Batista seizes power in military coup", description: "Fulgencio Batista overthrows the democratic government, establishing a dictatorship backed by US interests." },
  { id: "tl_moncada", date: "1953-07-26", title: "Castro attacks Moncada Barracks", description: "Castro's first revolutionary attempt fails. He is imprisoned and delivers 'History Will Absolve Me' speech." },
  { id: "tl_sierra", date: "1956-12-02", title: "Castro lands in Sierra Maestra", description: "Castro returns from exile in Mexico with 82 guerrilla fighters aboard the yacht Granma." },
  { id: "tl_revolution", date: "1959-01-01", title: "Cuban Revolution succeeds", description: "Batista flees Cuba. Castro's forces take Havana. Celebrations fill the streets." },
  { id: "tl_land_reform", date: "1959-05-17", title: "Agrarian Reform Law passed", description: "Cuba nationalizes foreign-owned land. US corporations lose billions in holdings." },
  { id: "tl_embargo", date: "1960-10-19", title: "US imposes trade embargo", description: "The United States cuts virtually all trade with Cuba in response to nationalizations." },
  { id: "tl_bay_of_pigs", date: "1961-04-17", title: "Bay of Pigs invasion", description: "CIA-trained Cuban exiles invade at the Bay of Pigs. The operation fails catastrophically." },
  { id: "tl_missile_deploy", date: "1962-07-01", title: "Soviet missiles begin arriving in Cuba", description: "The USSR secretly begins shipping nuclear missiles and personnel to Cuba." },
  { id: "tl_u2_discovery", date: "1962-10-14", title: "U-2 photographs reveal missiles", description: "American spy planes photograph missile launch sites under construction in Cuba." },
  { id: "tl_kennedy_speech", date: "1962-10-22", title: "Kennedy addresses the nation", description: "Kennedy reveals the missiles to the public and announces a naval 'quarantine' of Cuba." },
  { id: "tl_blockade", date: "1962-10-24", title: "Naval blockade begins", description: "US Navy ships surround Cuba. Soviet cargo ships approach. The world holds its breath." },
  { id: "tl_khrushchev_letter", date: "1962-10-26", title: "Khrushchev's personal letter to Kennedy", description: "Khrushchev sends an emotional letter proposing a deal. Castro sends a cable suggesting first strike." },
  { id: "tl_black_saturday", date: "1962-10-27", title: "Black Saturday — closest to nuclear war", description: "A U-2 is shot down over Cuba. Bobby Kennedy meets Dobrynin secretly. The world's closest brush with annihilation." },
  { id: "tl_resolution", date: "1962-10-28", title: "Crisis resolved", description: "Khrushchev agrees to remove missiles. Kennedy pledges not to invade Cuba. Secret Turkey deal hidden for decades." },
];

// Figures for motive tracking
export const KEY_FIGURES = [
  {
    id: "kennedy",
    name: "John F. Kennedy",
    role: "President of the United States",
    goals: ["Contain communism", "Appear strong domestically", "Avoid nuclear war", "Win re-election"],
    fears: ["Soviet expansion", "Appearing weak (especially after Bay of Pigs)", "Nuclear annihilation", "Military hawks forcing his hand"],
    pressures: ["Joint Chiefs demanding air strikes", "Public panic", "Congressional hawks", "Cold War credibility"],
    contradictions: ["Wanted peace but authorized Bay of Pigs", "Opposed air strikes but maintained blockade", "Publicly demanded unconditional withdrawal while secretly negotiating trade"],
    relatedDocs: ["doc_kennedy_address", "doc_excomm_transcript", "doc_secret_negotiations", "doc_bobby_kennedy_backchannel"],
  },
  {
    id: "khrushchev",
    name: "Nikita Khrushchev",
    role: "Premier of the Soviet Union",
    goals: ["Protect Cuba from US invasion", "Close the nuclear gap cheaply", "Prove Soviet strength to China", "Achieve Berlin leverage"],
    fears: ["US nuclear superiority (8:1 ratio)", "Encirclement by US bases", "Chinese criticism of weakness", "Losing Cuba = losing credibility"],
    pressures: ["Soviet military hawks", "Chinese accusations of cowardice", "Cuban demands", "Nuclear imbalance"],
    contradictions: ["Claimed missiles were defensive while secretly deploying them", "Wanted to project strength but ultimately compromised", "Protected Cuba but made the deal without consulting Castro"],
    relatedDocs: ["doc_khrushchev_letter", "doc_khrushchev_fears", "doc_khrushchev_memoirs", "doc_khrushchev_castro_rebuke"],
  },
  {
    id: "castro",
    name: "Fidel Castro",
    role: "Leader of Revolutionary Cuba",
    goals: ["Defend Cuban sovereignty", "Build socialist society", "Resist US imperialism", "Maintain revolutionary power"],
    fears: ["US invasion (justified by Bay of Pigs)", "Economic collapse from embargo", "Becoming a Soviet puppet", "Counter-revolution"],
    pressures: ["US embargo strangling economy", "Dependence on Soviet aid", "Internal opposition", "Need to deliver on revolutionary promises"],
    contradictions: ["Fought for freedom but created political prisons", "Claimed independence but depended on USSR", "Advocated nuclear first strike that would destroy Cuba", "Promised elections but never held them"],
    relatedDocs: ["doc_castro_speech_history", "doc_castro_khrushchev_cable", "doc_matthews_interview"],
  },
];

// Investigation questions that students try to answer
export const INVESTIGATION_QUESTIONS = [
  {
    id: "q_why_missiles",
    title: "Why did Khrushchev risk placing missiles in Cuba?",
    description: "Examine the strategic, political, and psychological reasons behind the Soviet decision.",
    requiredConnections: ["doc_turkey_missiles", "doc_bay_of_pigs", "doc_khrushchev_fears", "doc_arms_race_data"],
    relatedDocs: ["map_turkey_missiles", "doc_mongoose_ops", "doc_khrushchev_memoirs"],
  },
  {
    id: "q_embargo_impact",
    title: "How did the US embargo reshape Cuba?",
    description: "Trace the economic, social, and geopolitical consequences of cutting Cuba off from its largest trading partner.",
    requiredConnections: ["doc_sugar_trade", "doc_us_embargo", "doc_soviet_aid_records", "doc_cuban_life_before_after"],
    relatedDocs: ["doc_batista_economy", "civilian_exile_miami"],
  },
  {
    id: "q_hero_or_dictator",
    title: "Was Castro a revolutionary hero or a dictator?",
    description: "Compare the genuine achievements of the revolution with its human rights violations.",
    requiredConnections: ["prop_cuban_literacy", "doc_political_prisoners", "civilian_teacher_account", "civilian_exile_miami"],
    relatedDocs: ["doc_cuban_life_before_after", "doc_castro_speech_history"],
  },
  {
    id: "q_double_standards",
    title: "Did the US apply a double standard?",
    description: "Compare American missiles in Turkey with Soviet missiles in Cuba. Were the rules applied equally?",
    requiredConnections: ["doc_turkey_missiles", "map_turkey_missiles", "doc_soviet_un_response", "doc_monroe_doctrine"],
    relatedDocs: ["doc_secret_negotiations", "doc_khrushchev_memoirs"],
  },
  {
    id: "q_who_controlled",
    title: "Who really controlled the Cuban Missile Crisis?",
    description: "Examine how much power each leader actually had — and how much came down to luck.",
    requiredConnections: ["doc_excomm_transcript", "doc_castro_khrushchev_cable", "doc_cuban_fear_invasion", "doc_defcon_records"],
    relatedDocs: ["doc_bobby_kennedy_backchannel", "doc_khrushchev_castro_rebuke"],
  },
];

// Player progress defaults
export const DEFAULT_PROGRESS = {
  unlockedFiles: [
    "photo_batista_palace", "photo_sierra_maestra", "photo_missile_parade",
    "doc_matthews_interview", "doc_bay_of_pigs",
    "doc_sugar_trade", "doc_us_embargo", "doc_batista_economy",
    "doc_land_reform", "doc_monroe_doctrine",
    "doc_castro_speech_history",
    "prop_us_poster_red_cuba", "prop_soviet_poster_hands",
  ],
  madeConnections: [],
  analyzedDocs: [],
  completedQuestions: [],
  timelinePlaced: [],
  boardPositions: {},
};
